server:
  port: 80

eureka:
  instance:
    instance-id: cloud-consumer-order-80
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    register-with-eureka: true

spring:
  application:
    name:  cloud-consumer-order
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1 #采样率值介于 0 到 1 之间，1 则表示全部采集