server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      port: 8500
      host: 127.0.0.1
      discovery:
        hostname: ${spring.application.name}
        heartbeat:
          enabled: true