server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 09c599cc-aff7-482c-9674-756a275fa3b6
        group: local
management:
  endpoints:
    web:
      exposure:
        include: '*'
