server:
  port: 8001

eureka:
  instance:
    instance-id: cloud-provider-payment-8001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    register-with-eureka: true

spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1 #采样率值介于 0 到 1 之间，1 则表示全部采集

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.wjb.springcloud.entities    # 所有Entity别名类所在包


